apiVersion: v2
name: firehose-ethereum
description: A Helm chart for Kubernetes
type: application
version: 1.2.5
appVersion: v2.13.1-geth
keywords:
  - firehose
  - substreams
annotations:
  lookupName: "ghcr.io/streamingfast/firehose-ethereum"
