{{- $values := $.Values.fullMode }}
{{- $componentName := "op-node" }}
{{- $componentLabel := include "firehose-ethereum.componentLabelFor" $componentName }}
{{- if and (eq .Values.mode "full") $values.components.opnode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-firehose-{{ $componentName }}-svc
  labels:
    {{- include "firehose-ethereum.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "firehose-ethereum.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
  ports:
    - name: rpc
      port: 9545
      targetPort: 9545
      protocol: TCP
    - name: p2p-tcp
      port: 9222
      targetPort: 9222
      protocol: TCP
    - name: p2p-udp
      port: 9222
      targetPort: 9222
      protocol: UDP
{{- end }}