#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readme_path="${repo_root}/README.md"

begin_marker="<!-- BEGIN AUTOGENERATED AVAILABLE CHARTS -->"
end_marker="<!-- END AUTOGENERATED AVAILABLE CHARTS -->"

begin_count="$(awk -v marker="${begin_marker}" '$0 == marker { c++ } END { print c+0 }' "${readme_path}")"
end_count="$(awk -v marker="${end_marker}" '$0 == marker { c++ } END { print c+0 }' "${readme_path}")"

if [[ "${begin_count}" -ne 1 || "${end_count}" -ne 1 ]]; then
  echo "README.md must contain exactly one begin/end available charts marker block." >&2
  exit 1
fi

table_tmp="$(mktemp)"
rows_tmp="$(mktemp)"
out_tmp="$(mktemp)"

{
  echo "| Chart | Description | Current App Version |"
  echo "|---|---|---|"
} > "${table_tmp}"

for chart_yaml in "${repo_root}"/charts/*/Chart.yaml; do
  [[ -f "${chart_yaml}" ]] || continue

  chart_name="$(awk '/^name:[[:space:]]*/{sub(/^name:[[:space:]]*/, ""); gsub(/^"|"$/, ""); print; exit}' "${chart_yaml}")"
  chart_description="$(awk '/^description:[[:space:]]*/{sub(/^description:[[:space:]]*/, ""); gsub(/^"|"$/, ""); print; exit}' "${chart_yaml}")"
  chart_app_version="$(awk '/^appVersion:[[:space:]]*/{sub(/^appVersion:[[:space:]]*/, ""); gsub(/^"|"$/, ""); print; exit}' "${chart_yaml}")"

  printf '| `%s` | %s | `%s` |\n' "${chart_name}" "${chart_description}" "${chart_app_version}" >> "${rows_tmp}"
done

LC_ALL=C sort "${rows_tmp}" >> "${table_tmp}"

awk -v begin="${begin_marker}" -v end="${end_marker}" -v table_file="${table_tmp}" '
BEGIN {
  while ((getline line < table_file) > 0) {
    table = table line "\n"
  }
  close(table_file)
  in_block = 0
}
{
  if ($0 == begin) {
    print
    printf "%s", table
    in_block = 1
    next
  }
  if ($0 == end) {
    in_block = 0
    print
    next
  }
  if (!in_block) {
    print
  }
}
' "${readme_path}" > "${out_tmp}"

mv "${out_tmp}" "${readme_path}"
rm -f "${table_tmp}" "${rows_tmp}"
